# Generated by Django 2.1.7 on 2019-03-24 00:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='city name')),
                ('desc', models.CharField(max_length=200, verbose_name='city description')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'city',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='organization name')),
                ('desc', models.TextField(verbose_name='organization description')),
                ('click_num', models.IntegerField(default=0, verbose_name='click number')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favorite number')),
                ('image', models.ImageField(upload_to='org/%Y/%m')),
                ('address', models.CharField(max_length=300, verbose_name='organization address')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='organization city')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='teacher name')),
                ('work_years', models.IntegerField(default=0, verbose_name='work years')),
                ('work_company', models.CharField(max_length=50, verbose_name='work company')),
                ('work_position', models.CharField(max_length=40, verbose_name='work position')),
                ('points', models.CharField(max_length=50, verbose_name='teaching points')),
                ('click_num', models.IntegerField(default=0, verbose_name='click number')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='favorite number')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='time of adding')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='work organization')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teacher',
            },
        ),
    ]
