# Generated by Django 2.1.7 on 2019-04-01 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190330_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'verbose_name': 'resources', 'verbose_name_plural': 'resources'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'chapter', 'verbose_name_plural': 'chapter'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'video', 'verbose_name_plural': 'video'},
        ),
    ]
