# Generated by Django 2.1.7 on 2019-04-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190401_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='media/courses/%Y/%m', verbose_name='cover image'),
        ),
    ]
