# Generated by Django 2.1.7 on 2019-03-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(default='', max_length=50, unique=True, verbose_name='nickname')),
                ('birthday', models.DateField(null=True, verbose_name='birthday')),
                ('gender', models.CharField(choices=[('male', 'make'), ('female', 'female')], default='female', max_length=10)),
                ('address', models.CharField(default='', max_length=500)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y/%m')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profile',
            },
        ),
    ]
