# Generated by Django 2.1.7 on 2019-03-23 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190323_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='verify code')),
                ('email', models.EmailField(max_length=50, verbose_name='email address')),
                ('send_type', models.CharField(choices=[('sign up', 'register'), ('forget', 'retrive password')], max_length=10)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'email verification code',
                'verbose_name_plural': 'email verification code',
            },
        ),
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='name')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='page banner')),
                ('url', models.URLField(verbose_name='url address')),
                ('index', models.IntegerField(default=100, verbose_name='order')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'page banner image',
                'verbose_name_plural': 'page banner image',
            },
        ),
    ]
